#set document(title: "typst-to-web Demo", author: "Demo Author")
#set page(paper: "a4", margin: (x: 2.5cm, y: 3cm))
#set text(font: "New Computer Modern", size: 11pt)
#set heading(numbering: "1.")
#set math.equation(numbering: "(1)")

#align(center)[
  #text(size: 24pt, weight: "bold")[typst-to-web Demo]
  #v(0.5em)
  #text(size: 13pt, fill: gray)[A showcase of math, figures, and structure]
  #v(0.5em)
  Demo Author
  #v(2em)
]

= Introduction

This document demonstrates the capabilities of *typst-to-web*, a tool that
converts Typst documents into beautiful, self-contained HTML websites.

The approach uses the official Typst compiler to render pages as SVG — which
means _every_ Typst feature works perfectly: math, custom packages, cetz
figures, and more.

== Motivation

Existing web compilers struggle with:
- Complex mathematical expressions
- Package-dependent content (cetz, fletcher, etc.)
- Custom fonts and layouts

Our solution: delegate all rendering to the official Typst CLI.

= Mathematics

Inline math works naturally: the quadratic formula is $x = (-b plus.minus sqrt(b^2 - 4 a c)) / (2a)$.

Display equations are rendered with full fidelity:

$
  integral_0^infinity e^(-x^2) dif x = frac(sqrt(pi), 2)
$ <eq-gaussian>

The Euler identity, often called the most beautiful equation in mathematics:

$
  e^(i pi) + 1 = 0
$ <eq-euler>

And Maxwell's equations in differential form:

$
  nabla dot.op bold(E) &= rho / epsilon_0 \
  nabla dot.op bold(B) &= 0 \
  nabla times bold(E) &= -partial bold(B) / (partial t) \
  nabla times bold(B) &= mu_0 (bold(J) + epsilon_0 partial bold(E) / (partial t))
$

== Linear Algebra

The singular value decomposition of a matrix $bold(A) in RR^(m times n)$:

$
  bold(A) = bold(U) bold(Sigma) bold(V)^top
$

where $bold(U) in RR^(m times m)$, $bold(Sigma) in RR^(m times n)$ (diagonal),
and $bold(V) in RR^(n times n)$ are all orthogonal matrices.

= Figures with CeTZ <sec-cetz>

#import "@preview/cetz:0.3.4"

#figure(
  cetz.canvas({
    import cetz.draw: *

    // coordinate axes
    line((-0.3, 0), (5.5, 0), mark: (end: ">", fill: black))
    line((0, -0.3), (0, 4.5), mark: (end: ">", fill: black))
    content((5.7, 0), $x$)
    content((0, 4.7), $y$)

    // parabola y = 0.3 x^2
    let pts = range(0, 40).map(i => {
      let x = i * 0.13
      (x, 0.3 * x * x)
    })
    catmull(..pts, stroke: blue + 1.5pt)

    // tangent at x=2, slope = 0.6*2 = 1.2, y = 0.3*4 = 1.2
    let x0 = 2; let y0 = 0.3 * x0 * x0; let m = 0.6 * x0
    line((x0 - 1.2, y0 - 1.2 * m), (x0 + 1.5, y0 + 1.5 * m),
      stroke: red + 1.2pt)

    // point
    circle((x0, y0), radius: 0.07, fill: red)
    content((x0 + 0.3, y0 + 0.3), $(2, 1.2)$)

    // labels
    content((3.5, 3.5), text(fill: blue)[$y = 0.3x^2$])
    content((4.2, 2.0), text(fill: red)[tangent])
  }),
  caption: [A parabola $y = 0.3x^2$ with its tangent at $x=2$, drawn with CeTZ.],
) <fig-parabola>

= Tables and Lists

#figure(
  table(
    columns: (auto, 1fr, 1fr, 1fr),
    inset: 8pt,
    align: (left, center, center, center),
    table.header(
      [*Format*], [*Math*], [*Figures*], [*Self-contained*],
    ),
    [typst-to-web (SVG)], [✓], [✓], [✓],
    [typst HTML export], [✗], [✗], [✗],
    [pandoc],            [partial], [✗], [✓],
    [LaTeX → HTML],      [✓], [partial], [✗],
  ),
  caption: [Comparison of Typst-to-web conversion tools.],
)

= Code Listings

The tool is written in Python. The core compilation step:

```python
import subprocess, tempfile
from pathlib import Path

def compile_to_svgs(typ_path):
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "page-{p}.svg"
        subprocess.run(
            ["typst", "compile", str(typ_path), str(out), "--format", "svg"],
            check=True,
        )
        return [f.read_text() for f in sorted(Path(tmp).glob("page-*.svg"))]
```

= Conclusion

typst-to-web leverages the full power of the official Typst compiler, producing
pixel-perfect SVG output that is then wrapped in a rich, interactive HTML
viewer with:

+ Full-text search across all pages
+ Table of contents with click-to-navigate
+ Dark / light mode toggle
+ Zoom controls and keyboard navigation
+ Print-friendly output
+ Zero external runtime dependencies

All Typst features — including complex math (@eq-gaussian, @eq-euler), cetz
figures (@fig-parabola), and custom packages — are rendered correctly because we
use the real compiler.

#v(2em)
#align(center)[
  #text(size: 10pt, fill: gray)[
    Generated by typst-to-web · https://github.com/example/typst-to-web
  ]
]
